---
dotfiles_repo_url: https://github.com/quark-zju/dotfiles.git
dotfiles_repo_dest: "{{ ansible_facts.user_dir }}/src/dotfiles"

dotfiles_gitconfig_local_path: "{{ ansible_facts.user_dir }}/.gitconfig.local"

dotfiles_link_parent_dirs:
  - "{{ ansible_facts.user_dir }}/.config"

dotfiles_links:
  - dest: "{{ ansible_facts.user_dir }}/.zshrc"
    src: src/dotfiles/.zshrc
  - dest: "{{ ansible_facts.user_dir }}/.config/nvim"
    src: ../src/dotfiles/.config/nvim
  - dest: "{{ ansible_facts.user_dir }}/.config/zsh"
    src: ../src/dotfiles/.config/zsh
  - dest: "{{ ansible_facts.user_dir }}/.gitconfig"
    src: src/dotfiles/.gitconfig
  - dest: "{{ ansible_facts.user_dir }}/.config/git-hooks"
    src: ../src/dotfiles/.config/git-hooks

dotfiles_opencode_config_dir: "{{ ansible_facts.user_dir }}/.config/opencode"

dotfiles_opencode_links:
  - dest: "{{ dotfiles_opencode_config_dir }}/AGENTS.md"
    src: ../../src/dotfiles/.config/opencode/AGENTS.md
  - dest: "{{ dotfiles_opencode_config_dir }}/opencode.json"
    src: ../../src/dotfiles/.config/opencode/opencode.json
  - dest: "{{ dotfiles_opencode_config_dir }}/plugins"
    src: ../../src/dotfiles/.config/opencode/plugins"

dotfiles_codex_agents_link:
  dest: "{{ ansible_facts.user_dir }}/.codex/AGENTS.md"
  src: ../src/dotfiles/.config/opencode/AGENTS.md
