all:
  children:
    linux:
      hosts:
        localhost:
          ansible_connection: local
        sf:
          ansible_user: root
        hz:
        opi:
    opi_nodes:
      hosts:
        opi:
          ansible_user: root
