- name: Install risky module blacklist config
  ansible.builtin.template:
    src: blacklist.risky.conf.j2
    dest: "{{ linux_hardening_modprobe_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Apply Linux hardening sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | string }}"
    sysctl_file: "{{ linux_hardening_sysctl_file }}"
    state: present
    sysctl_set: true
    reload: "{{ ansible_loop.last }}"
  loop:
    - name: kernel.yama.ptrace_scope
      value: "{{ linux_hardening_ptrace_scope }}"
    # CVE-2026-23111 nf_tables use-after-free
    - name: kernel.unprivileged_userns_clone
      value: "{{ linux_hardening_unprivileged_userns_clone }}"
  loop_control:
    extended: true
